-- +goose Up
CREATE TABLE IF NOT EXISTS users (
	user_id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	username TEXT NOT NULL,
	email VARCHAR(25) NOT NULL UNIQUE,
    password TEXT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT NOW(),
	updated_at DATETIME NOT NULL DEFAULT NOW()
);

-- +goose Down
DROP TABLE IF EXISTS users;