// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type OrdersOrderStatus string

const (
	OrdersOrderStatusPending   OrdersOrderStatus = "pending"
	OrdersOrderStatusPaid      OrdersOrderStatus = "paid"
	OrdersOrderStatusCompleted OrdersOrderStatus = "completed"
	OrdersOrderStatusCancelled OrdersOrderStatus = "cancelled"
)

func (e *OrdersOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersOrderStatus(s)
	case string:
		*e = OrdersOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersOrderStatus: %T", src)
	}
	return nil
}

type NullOrdersOrderStatus struct {
	OrdersOrderStatus OrdersOrderStatus `json:"orders_order_status"`
	Valid             bool              `json:"valid"` // Valid is true if OrdersOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersOrderStatus), nil
}

type Cart struct {
	OrderID   int64     `json:"order_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type CartItem struct {
	ID         int64     `json:"id"`
	OrderID    int64     `json:"order_id"`
	ProductID  int64     `json:"product_id"`
	TotalPrice int64     `json:"total_price"`
	Quantity   int32     `json:"quantity"`
	CreatedAt  time.Time `json:"created_at"`
}

type Order struct {
	OrderID     int64             `json:"order_id"`
	UserID      int64             `json:"user_id"`
	CreatedAt   time.Time         `json:"created_at"`
	OrderStatus OrdersOrderStatus `json:"order_status"`
}

type OrderItem struct {
	ID         int64     `json:"id"`
	OrderID    int64     `json:"order_id"`
	ProductID  int64     `json:"product_id"`
	TotalPrice int64     `json:"total_price"`
	Quantity   int32     `json:"quantity"`
	CreatedAt  time.Time `json:"created_at"`
}

type Product struct {
	ProductID   int64     `json:"product_id"`
	ProductName string    `json:"product_name"`
	Price       int64     `json:"price"`
	Quantity    int32     `json:"quantity"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RefreshToken struct {
	ID           int64     `json:"id"`
	RefreshToken string    `json:"refresh_token"`
	IssuedAt     time.Time `json:"issued_at"`
	ExpiresAt    time.Time `json:"expires_at"`
	UserID       int64     `json:"user_id"`
}

type Role struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

type RolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type User struct {
	UserID    int64     `json:"user_id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Role      string    `json:"role"`
}

type UserPermission struct {
	ID         int64  `json:"id"`
	Permission string `json:"permission"`
}

type UserRole struct {
	ID   int64  `json:"id"`
	Role string `json:"role"`
}
