// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO orders(user_id)
VALUES (?)
`

func (q *Queries) CreateOrder(ctx context.Context, userID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder, userID)
}

const createOrderItem = `-- name: CreateOrderItem :execresult
INSERT INTO order_items (order_id, product_id, quantity, total_price)
VALUES (?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	OrderID    int64 `json:"order_id"`
	ProductID  int64 `json:"product_id"`
	Quantity   int32 `json:"quantity"`
	TotalPrice int64 `json:"total_price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.TotalPrice,
	)
}

const createProduct = `-- name: CreateProduct :execresult
INSERT INTO products (product_name, price, quantity)
VALUES (?, ?, ?)
`

type CreateProductParams struct {
	ProductName string `json:"product_name"`
	Price       int64  `json:"price"`
	Quantity    int32  `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProduct, arg.ProductName, arg.Price, arg.Quantity)
}

const createRefreshToken = `-- name: CreateRefreshToken :execresult
INSERT INTO refresh_tokens (refresh_token, user_id, issued_at, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateRefreshTokenParams struct {
	RefreshToken string    `json:"refresh_token"`
	UserID       int64     `json:"user_id"`
	IssuedAt     time.Time `json:"issued_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRefreshToken,
		arg.RefreshToken,
		arg.UserID,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (username, email, password)
VALUES (?, ?, ?)
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Username, arg.Email, arg.Password)
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE product_id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, productID)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE user_id = ?
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE email = ?
`

func (q *Queries) DeleteUser(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, email)
	return err
}

const listOrder = `-- name: ListOrder :one
SELECT order_id, user_id, created_at FROM orders
WHERE order_id = ?
`

func (q *Queries) ListOrder(ctx context.Context, orderID int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, listOrder, orderID)
	var i Order
	err := row.Scan(&i.OrderID, &i.UserID, &i.CreatedAt)
	return i, err
}

const listOrderItem = `-- name: ListOrderItem :one
SELECT id, order_id, product_id, total_price, quantity, created_at FROM order_items
WHERE id = ?
`

func (q *Queries) ListOrderItem(ctx context.Context, id int64) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, listOrderItem, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.TotalPrice,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, total_price, quantity, created_at FROM order_items
ORDER BY created_at DESC
`

func (q *Queries) ListOrderItems(ctx context.Context) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.TotalPrice,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT order_id, user_id, created_at FROM orders
ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(&i.OrderID, &i.UserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProduct = `-- name: ListProduct :one
SELECT product_id, product_name, price, quantity, created_at, updated_at FROM products WHERE product_id = ? LIMIT 1
`

func (q *Queries) ListProduct(ctx context.Context, productID int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, listProduct, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.ProductName,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT product_id, product_name, price, quantity, created_at, updated_at FROM products 
ORDER BY updated_at
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUser = `-- name: ListUser :one
SELECT user_id, username, email, password, created_at, updated_at, refresh_token_id FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) ListUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, listUser, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefreshTokenID,
	)
	return i, err
}

const listUserById = `-- name: ListUserById :one
SELECT user_id, username, email, password, created_at, updated_at, refresh_token_id FROM users WHERE user_id = ? LIMIT 1
`

func (q *Queries) ListUserById(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, listUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefreshTokenID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, username, email, password, created_at, updated_at, refresh_token_id FROM users
ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RefreshTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductQuantity = `-- name: UpdateProductQuantity :execresult
UPDATE products
SET quantity = ?
WHERE product_id = ?
`

type UpdateProductQuantityParams struct {
	Quantity  int32 `json:"quantity"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) UpdateProductQuantity(ctx context.Context, arg UpdateProductQuantityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProductQuantity, arg.Quantity, arg.ProductID)
}

const updateRefreshToken = `-- name: UpdateRefreshToken :execresult
UPDATE refresh_tokens
SET refresh_token = ?,
    issued_at = ?,
    expires_at = ?
WHERE user_id = ? AND id = ?
`

type UpdateRefreshTokenParams struct {
	RefreshToken string    `json:"refresh_token"`
	IssuedAt     time.Time `json:"issued_at"`
	ExpiresAt    time.Time `json:"expires_at"`
	UserID       int64     `json:"user_id"`
	ID           int64     `json:"id"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRefreshToken,
		arg.RefreshToken,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.UserID,
		arg.ID,
	)
}
